// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvOfc90aZfHb6Cr8l0jKVy7KPdzbdMmHw',
    appId: '1:586484350784:web:705b4c7e71136d655104a5',
    messagingSenderId: '586484350784',
    projectId: 'learn-e3225',
    authDomain: 'learn-e3225.firebaseapp.com',
    storageBucket: 'learn-e3225.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHCwLoVVLI_ExUzGFA-Nil-55uTLXNzdA',
    appId: '1:586484350784:android:e3630e80d6cd42b15104a5',
    messagingSenderId: '586484350784',
    projectId: 'learn-e3225',
    storageBucket: 'learn-e3225.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClUg2PlRWbR1p4Ee9C8A46Mvdkn2d81V0',
    appId: '1:586484350784:ios:d10dbf22543ebfe75104a5',
    messagingSenderId: '586484350784',
    projectId: 'learn-e3225',
    storageBucket: 'learn-e3225.firebasestorage.app',
    iosBundleId: 'com.example.essertCoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClUg2PlRWbR1p4Ee9C8A46Mvdkn2d81V0',
    appId: '1:586484350784:ios:d10dbf22543ebfe75104a5',
    messagingSenderId: '586484350784',
    projectId: 'learn-e3225',
    storageBucket: 'learn-e3225.firebasestorage.app',
    iosBundleId: 'com.example.essertCoffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvOfc90aZfHb6Cr8l0jKVy7KPdzbdMmHw',
    appId: '1:586484350784:web:1f5b7b7bd5540ac65104a5',
    messagingSenderId: '586484350784',
    projectId: 'learn-e3225',
    authDomain: 'learn-e3225.firebaseapp.com',
    storageBucket: 'learn-e3225.firebasestorage.app',
  );
}
